[package]
name = "crewai-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
rayon = "1.8"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
log = "0.4"
thiserror = "1.0"  # For better error handling 