version: '3.8'
services:
  solnai:
    image: mintplexlabs/solnai
    container_name: solnai
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    env_file:
      - .env
    volumes:
      - solnai_storage:/app/server/storage
      - ./.env:/app/server/.env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  solnai_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nvidia/system_monitoring/SolnAI/storage 