# Default configuration for AutoGroq

# API configuration
api:
  groq_api_key: ${GROQ_API_KEY}
  langsmith_api_key: ${LANGCHAIN_API_KEY}
  langsmith_api_url: ${LANGCHAIN_ENDPOINT}

# Agent configuration
agents:
  default_model: "llama3-70b-8192"
  default_temperature: 0.7
  default_max_tokens: 4096

# Workflow configuration
workflows:
  default_type: "dynamic_team"
  default_team_size: 3
  max_iterations: 10

# Integration configuration
integrations:
  crewai_rust:
    execution_mode: "parallel"
  langgraph:
    enabled: true
  langsmith:
    enabled: true
    default_project: "autogroq"

# Logging configuration
logging:
  level: "INFO"
  format: "{time} | {level} | {message}"
  file: "logs/autogroq.log"

# Storage configuration
storage:
  type: "file"
  path: "data"
